controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    cmd_vel_timeout: 0.25

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.30
    wheel_radius: 0.05

    publish_rate: 30.0

    odom_frame_id: odom
    base_frame_id: base_footprint

    enable_odom_tf: false #earlier true but changed to false, bcs of ekf node 
    publish_odom: true
    use_stamped_vel: true
